'''
Some utility functions to simplify loading and saving of IR models
generated by the framework
'''

import pickle
import os
import tvm
from tvm import relay

def save_model(model, params=None, meta=None, path=".models/sample",
               model_name="sample.ir", param_name="some.params"):
    '''
    Saves an IR model and parameters
    '''

    # Save the model as an .ir file
    os.makedirs(path, exist_ok=True)
    with open(os.path.join(path,model_name), "w") as file:
        file.write(str(model))

    if params != None:
        with open(os.path.join(path, param_name), "wb") as file:
            file.write(tvm.runtime.save_param_dict(params))
    
    if meta != None:
        name = model_name.split(".")[0] + ".pkl"
        with open(os.path.join(path,name), "wb") as file:
            pickle.dump(meta, file)

def load_model(path=".models/sample", model_file="sample.ir", param_file="weights.params", meta_consts=None, adapt_out_info=False):
    '''
    Loads a saved IR model, generated by `ir_generation.py`
    '''

    # Version - using the same as `tiny-training` to avoid strange issues
    SEMVER = '#[version = "0.0.5"]\n'
    
    # Read the IR and save it
    with open(os.path.join(path,model_file), 'r') as file:
        ir_code = file.read()
        ## TODO - If never used, remove
        if adapt_out_info:
            lines = ir_code.split("\n")
            segments = lines[0].split("")
            segments[-1] = "{"
            line_1 = "".join(segments)
            lines[0] = line_1
            ir_code = "\n".join(lines)

    # Create a meta table with all meta consts stored when creating the IR
    meta_table = None
    if meta_consts != None:
        with open(os.path.join(path, meta_consts), 'rb') as meta_file:
            meta_table = pickle.load(meta_file)
            meta_table = {
                "relay.Constant": [
                    relay.const(_, dtype=str(_.dtype)) for _ in meta_table
                ]
            }
    

    # Parse the loaded IR
    model_expression = tvm.parser.parse(
        SEMVER + ir_code, # Source
        "from_string", # Source fn - indicates it is a string
        None, # No init module
        meta_table # The created meta table
    )

    model = model_expression
    model = relay.transform.InferType()(model)

    # Load params
    with open(os.path.join(path, param_file), "rb") as param_file:
        binary_params = param_file.read()
    
    params = dict(tvm.runtime.load_param_dict(binary_params))

    return model, params